included:
  - Strangers
  - StrangersTests
  - StrangersKIFUITests

excluded:
  - StrangersTests/Sources/Mocks/Sourcery/AutoMockable.generated.swift
  - Strangers/Sources/Supports/Helpers/Rswift/R.generated.swift
  - Pods
  - Derived
  - DerivedData

opt_in_rules:
  - empty_enum_arguments        # Discourages empty arguments in enum cases (use explicit cases like `.myCase()`).
  - empty_string                # Ensures string literals are not empty unless necessary.
  - private_over_fileprivate    # Prefer `private` over `fileprivate` unless absolutely necessary.
  - sorted_imports              # Enforces alphabetical import sorting.

# Disable Rules (Project/Team Preferences)
disabled_rules:
  - force_cast                  # Disable if you prefer explicit `as!` in controlled cases.
  - force_unwrapping            # Allow `!` if it's justified in specific situations.
  - line_length                 # Disable for flexibility in line wrapping.
  - identifier_name             # Allow short variable names like `i`, `x`, etc.

identifier_name:
  excluded:
    - id
line_length:
  ignores_function_declarations: true
  ignores_comments: true
modifier_order:
  preferred_modifier_order:
    - acl
    - setterACL
    - override
    - dynamic
    - mutators
    - lazy
    - final
    - required
    - convenience
    - typeMethods
    - owned
nesting:
  type_level:
    warning: 2
number_separator:
  minimum_fraction_length: 10
trailing_whitespace:
  ignores_empty_lines: true
implicit_return:
  included:
    - closure
    - getter
    - function
